# general
title: PicoCTF 2025 Writeups
description: Writeups for the 2025 PicoCTF challenges I have completed
author: Bsnookie9
# theme
theme: jekyll-theme-hacker
# Github flavored markdown
markdown: GFM
